Repository flow2ml/Flow2ML, pull requests merged in 2021-04, with the labels that each got.

#38 update gitignore
  .gitignore
Labels: gssoc21, level1

#39 Fix Data_Loader.py
  README.md
  flow2ml/Data_Loader.py
Labels: gssoc21, level3

#11 Update README
  README.md
Labels: gssoc21, level0

#19 Added welcome bot
  .github/config.yml
Labels: gssoc21, level1

#15 Status Bar attached to readme.md file
  README.md
Labels: gssoc21, level1

#45 Readme enhanced
  README.md
Labels: gssoc21, level0

#43 Add Github workflow
  .github/workflows/publish_pypi.yml
  .github/workflows/python_linter.yml
Labels: gssoc21, level2
