Repository flow2ml/Flow2ML, pull requests merged in 2021-05, with the labels that each got.

#67 Add Flip augmentation technique
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
Labels: enhancement, good first issue, gssoc21, level3

#73 Data Augumentation -- Rotation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
  requirements.txt
Labels: enhancement, good first issue, gssoc21, level3

#69 Automating Results
  .gitignore
  README.md
  flow2ml/Auto_Results.py
  flow2ml/README.md
  flow2ml/__init__.py
  requirements.txt
Labels: enhancement, gssoc21, help wanted, level3

#78 Added bilateral filter
  README.md
  flow2ml/Filters.py
  flow2ml/README.md
Labels: good first issue, gssoc21, level3

#82 Add cropping augmentation technique
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#81 automated analysis support for tensorflow models
  README.md
  flow2ml.egg-info/SOURCES.txt
  flow2ml/README.md
  flow2ml/Tf_Results.py
  flow2ml/__init__.py
Labels: gssoc21, level3

#74 Improved code standards as per PEP8
  flow2ml/Data_Augumentation.py
  flow2ml/Data_Loader.py
  flow2ml/Filters.py
  flow2ml/Flow.py
  setup.py
Labels: gssoc21, level3

#84 Updated requirements.txt
  requirements.txt
Labels: bug, gssoc21, level1

#89 Add scaling operation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#93 Add zoom augmentation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#98 Test codebase with greyscale
  README.md
Labels: gssoc21, level2

#99 Added the code for histogram Equalisation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#97 deployed tensorflow models
  flow2ml/Data_Augumentation.py
Labels: gssoc21, level3

#102 Added greyscale augmentation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#104 added code for CLAHE operation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level2

#110 Allow dataloader to split data without preprocessing
  flow2ml/Data_Loader.py
Labels: bug, gssoc21, level3

#113 Added the code for morphological transformations
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level2

#114 Improve code quality
  flow2ml/Auto_Results.py
  flow2ml/Data_Augumentation.py
  flow2ml/Data_Loader.py
  flow2ml/Filters.py
  flow2ml/Flow.py
  flow2ml/Tf_Results.py
Labels: gssoc21, level3

#116 Added code for Thresholding augmentation
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#117 Added original unit tests
  .gitignore
  README.md
  requirements.txt
  tests/unit/README.md
  tests/unit/Tests.py
Labels: gssoc21, level3

#120 Added code for Changing Color Space
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level2

#122 Updated requirements
  README.md
  requirements.txt
Labels: bug, gssoc21, level2

#123 Connect aug filters
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Filters.py
  flow2ml/Flow.py
Labels: gssoc21, level3

#119 added code for deployment of tensorflow
  README.md
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#126 Score images using BRISQUE
  README.md
  flow2ml/Auto_Results.py
  flow2ml/Flow.py
  flow2ml/Image_Quality.py
  flow2ml/README.md
  flow2ml/Tf_Results.py
  requirements.txt
Labels: gssoc21, level3

#128 added code for canny edge detector
  README.md
  flow2ml/Filters.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level2

#135 Fix bugs
  README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Filters.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: bug, gssoc21, level3

#137 Fix bugs in model deployment
  README.md
  flow2ml/Flow.py
Labels: bug, gssoc21, level3

#138 Add entropy scores
  README.md
  flow2ml/Flow.py
  flow2ml/Image_Quality.py
  flow2ml/README.md
Labels: gssoc21, level3

#140 Detect blur using Laplacian filter
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#142 Fix path errors in results
  README.md
  flow2ml/Auto_Results.py
  flow2ml/Tf_Results.py
Labels: gssoc21, level3

#144 Move sample code
  README.md
  examples/README.md
Labels: gssoc21, level1

#145 Add examples
  examples/horses_vs_humans.ipynb
Labels: gssoc21, level3

#146 Reorder code
  examples/README.md
Labels: gssoc21, level1

#147 Making code compatible enough for non-image datasets
  examples/README.md
  flow2ml/Process_Csv.py
  flow2ml/README.md
  flow2ml/__init__.py
Labels: gssoc21, level3

#148 add log transform
  examples/README.md
  flow2ml/Data_Augumentation.py
  flow2ml/Flow.py
  flow2ml/README.md
Labels: gssoc21, level3

#149 visualise csv
  examples/README.md
  flow2ml/Process_Csv.py
  flow2ml/README.md
Labels: gssoc21, level3

#150 Fix get dataset issues
  examples/README.md
  examples/horses_vs_humans.ipynb
  flow2ml/Data_Loader.py
  flow2ml/Flow.py
Labels: gssoc21, level3
